In [2]:
#Vetores

#Importanto biblioteca
import numpy as np

#Criando uma lista e alocando os seus valores no vetor vet
lista=[1,2,3,4,5]
vet=np.array(lista)
print(type(vet))
print(vet)


<class 'numpy.ndarray'>
[1 2 3 4 5]


In [4]:
#Matrizes

#Importanto biblioteca
import numpy as np
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(matriz))
print(matriz)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#Importanto biblioteca
import numpy as np
vetDias = np.array(['segunda','terça','quarta','quinta','sexta','sabado','domingo'])
print(vetDias)
print(vetDias[4])
print(vetDias[6])

['segunda' 'terça' 'quarta' 'quinta' 'sexta' 'sabado' 'domingo']
sexta
domingo


In [8]:
#Importanto biblioteca
import numpy as np
tupla=(1,2,3)
#Criando um vetor a partir de uma lista
vetNum = np.array(tupla)
print(type(vetNum))
print(vetNum)

<class 'numpy.ndarray'>
[1 2 3]


In [17]:
#Importanto biblioteca
import numpy as np
vetNum= np.array([4,16,64,625])
print(vetNum)
print(f"Maior número do vetor: {max(vetNum)}")
print(f"Menor número do vetor: {min(vetNum)}")
print(f"Soma número do vetor: {sum(vetNum)}")
print(f"Quantidade de números do vetor: {len(vetNum)}")
print(f"Mediana dos números do vetor: {np.median(vetNum)}")
print(f"Média de números do vetor: {np.mean(vetNum)}")
print(f"Raíz quadrada dos números do vetor: {np.sqrt(vetNum)}")


[  4  16  64 625]
Maior número do vetor: 625
Menor número do vetor: 4
Soma número do vetor: 709
Quantidade de números do vetor: 4
Mediana dos números do vetor: 40.0
Média de números do vetor: 177.25
Raíz quadrada dos números do vetor: [ 2.  4.  8. 25.]
