In [3]:
#Vetor = estrutura especial
#Armazena dados do mesmo tipo
#Utiliza a biblioteca numpy

import numpy as np
#"np" - abreviação de np

#Criando uma lista para transformar em vetor
lista = [10,11,12,13,14]
vetor = np.array(lista)

print(type(vetor))
print(f"Lista: {lista}")
print(f"Vetor: {vetor}")

#Convertendo vetor para lista
lista2=list(vetor)
vetor = np.array(lista2)

<class 'numpy.ndarray'>
Lista: [10, 11, 12, 13, 14]
Vetor: [10 11 12 13 14]


In [4]:
import numpy as np

lista = ['a','b','c','d','e']
vetor = np.array(lista)

print(f"Vetor: {vetor}")
print(f"Posição 0: {vetor[0]}")
print(f"Posição 4: {vetor[4]}")
print(f"Posição -1: {vetor[-1]}")
print(f"Posição -2: {vetor[-2]}")


Vetor: ['a' 'b' 'c' 'd' 'e']
Posição 0: a
Posição 4: e
Posição -1: e
Posição -2: d


In [9]:
import numpy as np

tupla=(10,20,30,40)
vetor=np.array(tupla)

print("Imprimindo posições do vetor:")
for numero in range(len(vetor)):
    print(numero)

print("Imprimindo conteúdo do vetor:")
for numero in vetor:
    print(numero)

Imprimindo posições do vetor:
0
1
2
3
Imprimindo conteúdo do vetor:
10
20
30
40


In [22]:
import numpy as np
#Criando vetor vazio
vetor=np.array([])

for num in range(5):
  vetor = np.append(vetor,int(input("Digite um número:")))

print(f"Vetor: {vetor}")
#Ordenando vetor
vetor.sort()
print(f"Vetor ordenado: {vetor}")
#Invertendo os INDICES de um vetor
np.flip(vetor)
print(f"Vetor ordenado ao contrário: {vetor}")


Digite um número:5
Digite um número:4
Digite um número:3
Digite um número:2
Digite um número:1
Vetor: [5. 4. 3. 2. 1.]
Vetor ordenado: [1. 2. 3. 4. 5.]
Vetor ordenado ao contrário: [5. 4. 3. 2. 1.]


In [19]:
import numpy as np

lista = [1,2,3,4,5]
vetor = np.array(lista)

print(f"Vetor: {vetor}")
print(f"Soma das posições 2 e 3: {vetor[2]+vetor[3]}")

Vetor: [1 2 3 4 5]
Soma: 7


In [27]:
import numpy as np

vetor = np.array([1,2,3,4,5])
print(vetor)
#Inserindo valores no vetor
vetor = np.append(vetor, 100)
print(vetor)
vetor = np.append(vetor, 0)
print(vetor)

#Excluindo valores de um vetor
#Excluindo valor da posição 0
vetor = np.delete(vetor,0)
print(vetor)

#Alterando valor de uma posição
vetor[0]= 200
print(vetor)

[1 2 3 4 5]
[  1   2   3   4   5 100]
[  1   2   3   4   5 100   0]
[  2   3   4   5 100   0]
[200   3   4   5 100   0]


In [29]:
import numpy as np

vetor = np.array([1,2,3,4,5])
print(f"Vetor: {vetor}")
print(f"Maior valor: {max(vetor)}")
print(f"Menor valor: {min(vetor)}")
print(f"Soma dos valores: {sum(vetor)}")
print(f"Indices do vetor: {len(vetor)}")
print(f"Média: {(sum(vetor))/len(vetor)}")
print(f"Média-Outra forma: {np.mean(vetor)}")
print(f"Raíz quadrada: {np.sqrt(vetor)}")

Vetor: [1 2 3 4 5]
Maior valor: 5
Menor valor: 1
Soma dos valores: 15
Indices do vetor: 5
Média: 3.0
Média-Outra forma: 3.0
Raíz quadrada: [1.         1.41421356 1.73205081 2.         2.23606798]


In [31]:
import numpy as np


vetor = np.array([1,2,3,])
vetor2 = np.array([4,5,6])
#Somando cada indice do vet1 com o indice
#correspondente no vet2
vetor3 = vetor+vetor2
vetor4 = vetor-vetor2
vetor5 = vetor*vetor2
print(vetor)
print(vetor2)
print(vetor3)
print(vetor4)
print(vetor5)



[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
